name: main

on:
  push:
    # Only build branches on push, tags will be handled by 'release' job.
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            freebsd-amd64,
            linux-amd64,
            linux-arm,
            linux-arm64,
            openbsd-amd64,
            windows-x64,
          ]
        include:
          - target: linux-amd64
            os: linux
            arch: amd64
            ext: ""
          - target: linux-arm64
            os: linux
            arch: arm64
            ext: ""
          - target: linux-arm
            os: linux
            arch: arm
            ext: ""
          - target: freebsd-amd64
            os: freebsd
            arch: amd64
            ext: ""
          - target: openbsd-amd64
            os: openbsd
            arch: amd64
            ext: ""
          - target: windows-x64
            os: windows
            arch: amd64
            ext: ".exe"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare Build Environment
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p build/${{ matrix.target }}
          go build -ldflags "-s -w" -o build/${{ matrix.target }}/ ./...

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: qtv-${{ matrix.target }}
          path: build/${{ matrix.target }}/qtv*
          compression-level: 9
          retention-days: 3

  upload:
    needs: build
    runs-on: ubuntu-latest
    # if: github.repository == 'QW-Group/qtv' && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'release')
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          path: build

      # - name: Setup SSH
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: |
      #     ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #     ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set date
        run: echo "DATE=$(TZ='Europe/Amsterdam' date '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Determine type
          IS_RELEASE=false
          IS_SNAPSHOT=false

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            IS_RELEASE=true
          else
            IS_SNAPSHOT=true
          fi

          # Process builds
          for target_dir in build/*; do
            target_name=$(basename "$target_dir")
            bin_file=$(find "$target_dir" -maxdepth 1 -type f -name "qtv*")
            checksum_file="$bin_file.md5"

            # Generate checksum
            md5sum "$bin_file" > "$checksum_file"

            if $IS_RELEASE; then
              DEST_DIR=upload/releases/${GITHUB_REF_NAME}/${target_name}
              LATEST_DIR=upload/releases/latest/${target_name}
            else
              DEST_DIR=upload/snapshots/${target_name}
              LATEST_DIR=upload/snapshots/latest/${target_name}
            fi

            mkdir -p "$DEST_DIR" "$LATEST_DIR"

            # Copy binaries and checksums
            cp "$bin_file" "$checksum_file" "$DEST_DIR/"
            cp "$bin_file" "$checksum_file" "$LATEST_DIR/"

            # For snapshots, append date and short SHA
            if $IS_SNAPSHOT; then
              for file in "$DEST_DIR"/qtv*; do
              mv "$file" "$DEST_DIR/${DATE}_${GITHUB_SHA::7}_$(basename "$file")"
              done
            fi
          done

          # SFTP upload
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            remote_dir=/releases
            local_dir=upload/releases
          else
            remote_dir=/snapshots
            local_dir=upload/snapshots
          fi

          echo $remote_dir
          tree $local_dir

          # sftp -rp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} <<< $"put -rp $local_dir/* $remote_dir"
