name: main

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    if: github.repository == 'vikpe/qtv'
    name: build (${{ matrix.os }}-${{ matrix.arch }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: freebsd
            arch: amd64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: arm
          - os: openbsd
            arch: amd64
          - os: windows
            arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare Build Environment
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          OUTPUT_DIR="build/${{ matrix.os }}/${{ matrix.arch }}"
          mkdir -p ${OUTPUT_DIR}
          go build -ldflags "-s -w" -o ${OUTPUT_DIR} ./...

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: qtv-${{ matrix.os }}-${{ matrix.arch }}
          path: build/${{ matrix.os }}/${{ matrix.arch }}/qtv*
          compression-level: 9
          retention-days: 3

  upload:
    if: github.repository == 'vikpe/qtv'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # if: github.repository == 'QW-Group/qtv' && ((github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'release')
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      # - name: Setup SSH
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   shell: bash
      #   run: |
      #     ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
      #     ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Get release date
        run: |
          REF_NAME="${{ github.ref_name || github.event.release.tag_name }}"
          RELEASE_DATE=$(git log -1 --format=%cI "$REF_NAME")
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Upload to builds.quakeworld.nu
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Build file structure for uploading
          # snapshots:
          #  upload/snapshots/latest/$os/$arch/$filename
          #  upload/snapshots/$os/$arch/$prefix_$filename
          # releases:
          #  upload/releases/latest/$os/$arch/$filename
          #  upload/releases/$tag/$os/$arch/$filename

          set -e

          upload_dir="${GITHUB_WORKSPACE}/upload"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            main_dir="${upload_dir}/releases/${{ github.ref_name }}"
            latest_dir="${upload_dir}/releases/latest"
            prefix=""
            upload_prefix="releases"
          else
            main_dir="${upload_dir}/snapshots"
            latest_dir="${upload_dir}/snapshots/latest"
            date=$(TZ="Europe/Amsterdam" date "+%Y%m%d-%H%M%S")
            prefix="${date}_${GITHUB_SHA::7}_"
            upload_prefix="snapshots"
          fi

          # Collect upload structure
          for artifact in artifacts/*/*; do
            artifact_file=$(basename "${artifact}")
            artifact_dir=$(dirname "${artifact}")

            IFS='-' read -r ezq os arch <<< "${artifact_dir}"

            mkdir -p "${main_dir}/${os}/${arch}" "${latest_dir}/${os}/${arch}"

            cp "${artifact}" "${main_dir}/${os}/${arch}/${prefix}${artifact_file}"
            cp "${artifact}" "${latest_dir}/${os}/${arch}/${artifact_file}"
          done

          # Set executable bit for all files
          find "${upload_dir}" -type f -exec chmod 755 {} +

          # Generate checksums
          for artifact in $(find "${upload_dir}" -type f); do
            artifact_file=$(basename "${artifact}")
            artifact_dir=$(dirname "${artifact}")
            (cd "${artifact_dir}" && md5sum "${artifact_file}" > "${artifact_file}.md5")
          done

          # Reset timestamp to time of commit
          find "${upload_dir}" -type f -exec touch --date="${RELEASE_DATE}" {} +

          echo "Upload artifacts:"
          tree ${upload_dir}

          # Upload
          # sftp -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/${upload_prefix} <<< $'put -rp upload/${upload_prefix}/*'
